### ISSUE TITLE
How to use microG with gapps compatibility?

### ISSUE THREAD

**Issue by Austcool-Walker** [AndyCGYan/android_device_lineage_gsi#2]
Hey I love your ROM on My Xiaomi Mi Pad Pro 5G (Enuma)
But when I DSU sideload the version with Signature spoofing and try to use.
https://github.com/Magisk-Modules-Alt-Repo/microG-GApps.git
With lineageOS 19.1 it doesn't work. (lineage-19.1-20221122-UNOFFICIAL-arm64_bvN-vndklite-secure.img.xz)
Is their a way a release of this build can include the microg version above? I'd really love to use this build of lineageOS but without the full blown google CIA/NSA malware in it. (I reliey heavily on microG + Google Voice for contacting family over LTE verizon internet.)
[This tablet lacks calling functionality from Verizons crusty old af towers.]

**Comment by MattTheTekie** [comment]
It lacks calling at least at a SIM level, due to Verizon and not giving everyone "cdma-less" on there legacy accounts, which is problematic when you switch a old Verizon SIM into a new VOLTE enabled device, but that's not related to this issue.

**Comment by AndyCGYan** [comment]
MG only works when manually installed into /system/priv-app (directly or as Magisk module).

DSU Sideloading conflicts with / disables Magisk in the first place, don't.

**Comment by MattTheTekie** [comment]
Ty.
