### ISSUE TITLE
Trebuchet breaks with Split Screen

### ISSUE THREAD

**Issue by reianayami** [AndyCGYan/android_device_lineage_gsi#3]
Not sure where to post this so hopefully it’s not wrong and you can help. I have your lineage 20 bvn variant in my iplay50 mini pro and it works great however when in split screen, trebuchet breaks and closes, so you have to hit the back button on both apps to bring it back

I tried replacing trebuchet with derplauncher, but since I have to make changes to prob-apps, it boot loops device. I wanted to try recompiling using derplauncher or pixel launcher just to see if I can get it to work

but any ideas or fixes or anything would be greatly appreciated!

the vdnk images aren’t compatible with my tablet so I can’t flash those to have access to priv-app.

**Comment by AndyCGYan** [comment]
This seems to have been fixed upstream since A14 QPR2, and I can't replicate anymore - closing.
